islandWidth: 10
islandHeight: 10
initialWolfCount: 50
initialFoxCount: 25
initialBearCount: 20
initialBoaCount: 50
initialEagleCount: 30
initialBoarCount: 90
initialBuffaloCount: 20
initialCaterpillarCount: 1000
initialDeerCount: 40
initialDuckCount: 180
initialGoatCount: 70
initialHorseCount: 30
initialMouseCount: 230
initialRabbitCount: 70
initialSheepCount: 60
simulationStepDuration: 10000